config/routes.rb
Rails.application.routes.draw do
  resource :match_queue, only: [:edit, :update]
  root 'welcome#index'
  resources :teams

  resources :scores

  get 'exportScores', to: 'welcome#export', as: 'export_scores'
  get 'exportGp', to: 'welcome#gp', as: 'export_gp_scores'
  get 'display', to: 'welcome#display', as: 'display'
  get 'pit', to: 'welcome#pit', as: 'pit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include Turbo::Broadcastable
  primary_abstract_class
end

app/models/match_queue.rb
class MatchQueue < ApplicationRecord
    before_create :confirm_singularity

    def confirm_singularity
        raise Exception.new("There can be only one.") if MatchQueue.count > 0
    end

    after_update_commit -> { broadcast_render_to :match, partial: 'welcome/matchRedraw' }
end

app/models/ranker.rb
class Ranker
  attr_reader :scores
  def initialize
    @scores = []
    Team.all.each do |team|
      max = [team.round1&.score || -1, team.round2&.score || -1, team.round3&.score || -1].sort.reverse
      scores << ([team.number] + max)
    end
    scores.sort_by! { |e| [e[1], e[2], e[3], -e[0]] }
    scores.reverse!

  end

  def teams
    @scores.map { |t| Team.find_by(number: t[0]) }
  end

  def ranks
    scores.map { |s| [ s[0], scores.index(s) + 1 ]}.to_h
  end
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :team

  scope :round1, -> { where(round: 1) }
  scope :round2, -> { where(round: 2) }
  scope :round3, -> { where(round: 3) }

  after_update_commit -> { 
    broadcast_render_to :scoreboard, partial: 'welcome/rankRedraw' 
    broadcast_render_to :pit, partial: 'welcome/pitRedraw' 
  }
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :scores

  def long_name
    "#{number} - #{name}"
  end

  def round1
    scores.round1.first_or_create(score: -1, gp_score: -1, round: 1)
  end

  def round2
    scores.round2.first_or_create(score: -1, gp_score: -1, round: 2)
  end

  def round3
    scores.round3.first_or_create(score: -1, gp_score: -1, round: 3)
  end

  def max
    @max = [round1&.score || -1, round2&.score || -1, round3&.score || -1].max
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :http_authenticate, :set_match_queue

  def http_authenticate
    return true unless ENV['SCOREPASSWORD']
    authenticate_or_request_with_http_basic do |username, password|
        username == 'scoreboard' && password == ENV['SCOREPASSWORD']
    end
  end

  def set_match_queue
    @match_queue = MatchQueue.find_or_create_by(id: 1)
  end
end

app/controllers/match_queues_controller.rb
class MatchQueuesController < ApplicationController
  before_action :set_match_queue, only: %i[ edit update ]

  # GET /match_queues/1/edit
  def edit
  end

  # PATCH/PUT /match_queues/1 or /match_queues/1.json
  def update
    respond_to do |format|
      if @match_queue.update(match_queue_params)
        format.html { redirect_to edit_match_queue_path, notice: "Match queue was successfully updated." }
        format.json { render :show, status: :ok, location: @match_queue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match_queue.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def match_queue_params
      params.require(:match_queue).permit(:name, :number)
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to new_score_path, notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:team_id, :score, :gp_score, :round)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.order(:number)
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_url, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_url(@team), notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def score
    @score = Score.new
  end

  def post_score
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to team_url(@team), notice: "Score was successfully posted." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :score, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:number, :name)
    end

    def score_params
      params.require(:score).permit(:team, :round, :score, :gp_score)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :http_authenticate, only: %i[index display]

  def index
  end

  def display
    render 'display', layout: 'scroller'
  end

  def export
    @teams = Team.order(:number)
    @ranks = Ranker.new.ranks
  end

  def gp
    @teams = Team.order(:number)
    @ranks = Ranker.new.ranks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(icon, variant="solid", *options)
    content_tag(:i, '', class: [
      'fa-fw',
      "fa-#{variant}",
      "fa-#{icon}",
      *options
      ]).html_safe
  end
end

app/helpers/match_queues_helper.rb
module MatchQueuesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegoScoreboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;700&family=Fira+Sans:wght@400;900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0aa9b30352.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/scroller.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegoScoreboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;700&family=Fira+Sans:wght@400;900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0aa9b30352.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="scroller">
    <%= yield %>
  </body>
</html>

app/views/match_queues/_form.html.erb
<%= form_with(model: match_queue) do |form| %>
  <% if match_queue.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match_queue.errors.count, "error") %> prohibited this match_queue from being saved:</h2>

      <ul>
        <% match_queue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div class="mt-3">
    <%= form.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/match_queues/_match_queue.html.erb
<div id="<%= dom_id match_queue %>">
  <p>
    <strong>Name:</strong>
    <%= match_queue.name %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= match_queue.number %>
  </p>

</div>

app/views/match_queues/edit.html.erb
<main>
  <h1>Editing match queue</h1>

  <%= render "form", match_queue: @match_queue %>
</main>

app/views/match_queues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Match queues</h1>

<div id="match_queues">
  <% @match_queues.each do |match_queue| %>
    <%= render match_queue %>
    <p>
      <%= link_to "Show this match queue", match_queue %>
    </p>
  <% end %>
</div>

<%= link_to "New match queue", new_match_queue_path %>

app/views/match_queues/new.html.erb
<h1>New match queue</h1>

<%= render "form", match_queue: @match_queue %>

<br>

<div>
  <%= link_to "Back to match queues", match_queues_path %>
</div>

app/views/match_queues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match_queue %>

<div>
  <%= link_to "Edit this match queue", edit_match_queue_path(@match_queue) %> |
  <%= link_to "Back to match queues", match_queues_path %>

  <%= button_to "Destroy this match queue", @match_queue, method: :delete %>
</div>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="columns">
    <div class="column">
      <%= form.label :score, class: 'label' %>
      <%= form.number_field :score, class: 'input' %>
    </div>

    <div class="column">
      <%= form.label :gp_score, class: 'label' %>
      <%= form.number_field :gp_score, class: 'input' %>
    </div>
  </div>

  <div>
    <%= form.submit 'OK', class: 'button is-success is-small' %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<%= turbo_frame_tag score do %>
  <%= score.score %> / <%= score.gp_score %> <%= link_to icon('edit'), edit_score_path(score) %>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= turbo_frame_tag @score do %>
<%= render "form", score: @score %>
<% end %>

<br>

<div>
  <%= link_to "Show this score", @score %> |
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/index.html.erb
<main>
<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score %>
    </p>
  <% end %>
</div>

<%= link_to "New score", new_score_path %>
</main>

app/views/scores/new.html.erb
<main>
<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>
</main>

app/views/scores/show.html.erb
<main>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", scores_path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>
</main>

app/views/welcome/_matchQueue.erb
<%= turbo_frame_tag 'match' do %>
  <div class="matchQueue">
    <span style="font-weight: bold;"><%= MatchQueue.first.name %></span>
    <span style="font-weight: bolder;">Match #<%= MatchQueue.first.number %></span>
  </div>
<% end %>

app/views/welcome/_matchRedraw.turbo_stream.erb
<%= turbo_stream.replace "match" do %>
  <%= render 'welcome/matchQueue' %>
<% end %>

app/views/welcome/_pitDisplay.erb
<%= turbo_frame_tag 'pit' do %>
  <div class="pitDisplay">
    <% Team.order(:number).to_a.each_slice(4).each do |row| %>
      <div class="columns is-align-items-center">
        <% row.each do |team| %>
          <div class="column is-2 has-text-right pr-4">
            <div class="num"><%= team.number %></div>
            <div class="name"><%= team.name %></div>
          </div>
          <div class="column is-1 pl-4">
            <div class="rank"><%= team.max || '-' %></div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/welcome/_pitRedraw.turbo_stream.erb
<%= turbo_stream.replace "pit" do %>
  <%= render 'welcome/pitDisplay' %>
<% end %>

app/views/welcome/_rankDisplay.html.erb
<%= turbo_frame_tag 'scoreboard' do %>
  <div class="rankScroller">
    <% Ranker.new.teams.each_with_index do |team, rank| %>
      <div class="columns is-align-items-center team">
        <div class="column is-1 rank mr-4">#<%= rank + 1%></div>
        <div class="column">
          <div class="num"><%= team.number %></div>
          <div class="name"><%= team.name %></div>
        </div>
        <div class="column is-2">
          <%= team.round1.score > 0 ? team.round1.score : '-' %>
        </div>
        <div class="column is-2">
          <%= team.round2.score > 0 ? team.round2.score : '-' %>
        </div>
        <div class="column is-2">
          <%= team.round3.score > 0 ? team.round3.score : '-' %>
        </div>
      </div>  
    <% end %>
  </div>
<% end %>

app/views/welcome/_rankRedraw.turbo_stream.erb
<%= turbo_stream.replace "scoreboard" do %>
  <%= render 'welcome/rankDisplay' %>
<% end %>

app/views/welcome/display.html.erb
<main id="scoreboardScroller">
  <%= turbo_stream_from 'scoreboard', style: 'position: absolute;' %>
  
  <%= render 'rankDisplay' %>
</main>
<%= turbo_stream_from 'match', style: 'position: absolute;' %>
<%= render 'matchQueue' %>

<script>
var translate = 0;
const windowHeight = window.innerHeight;
setInterval(() => {
    const tableHeight = document.getElementById("scoreboardScroller").getBoundingClientRect().height;
    document.getElementById("scoreboardScroller").style.transform = `translateY(${translate}px)`;
    translate--;
    if(translate <= (-1 * (tableHeight - 200))) {
        translate = windowHeight - 400;
    }
}, 33);

</script>

app/views/welcome/export.html.erb
<main>
  <p>
  The following should be ready to copy & paste into the Robot Game Scores sheet of OJS.
  </p>
  <table>
    <% @teams.each do |team| %>
      <tr>
        <td><%= @ranks[team.number] %></td>
        <td><%= team.number %></td>
        <td><%= team.max < 0 ? 0 : team.max %></td>
        <td><%= team.round1.score > 0 ? team.round1.score : 0 %></td>
        <td><%= team.round2.score > 0 ? team.round2.score : 0 %></td>
        <td><%= team.round3.score > 0 ? team.round3.score : 0 %></td>
      </tr>
    <% end %>
  </table>
</main>

app/views/welcome/gp.html.erb
<main>
  <p>
  The following should be ready to copy & paste into the Core Values sheet of OJS.
  </p>
  <table>
    <% @teams.each do |team| %>
      <tr>
        <td><%= team.round1.gp_score > 0 ? team.round1.gp_score : 0 %></td>
        <td><%= team.round2.gp_score > 0 ? team.round2.gp_score : 0 %></td>
        <td><%= team.round3.gp_score > 0 ? team.round3.gp_score : 0 %></td>
      </tr>
    <% end %>
  </table>
</main>

app/views/welcome/index.html.erb
<main class="has-text-centered">
  <div class="mt-6 mb-3 mx-4">
    <%= link_to icon('desktop') + " Scrolling Score Display", display_path, class: 'button is-primary is-large' %>
    <%= link_to icon('clipboard-list') + " Pit Display", pit_path, class: 'button is-light is-large' %>
  </div>

  <div class="mb-3 mx-4">
    <%= link_to icon('calculator') + " Official Score Calculator", 'https://eventhub.firstinspires.org/scoresheet', class: 'button is-success' %>
    <%= link_to icon('edit') + " Score Entry", teams_path, class: 'button is-info' %>
  </div>

  <div class="mb-3 mx-4">
    <%= link_to icon('hourglass-half') + " Queueing Status", edit_match_queue_path, class: 'button is-dark' %>
  </div>

  <div class="mb-6 mx-4">
    <%= link_to icon('file-excel') + " Export Scores", export_scores_path, class: 'button is-warning' %>
    <%= link_to icon('user-tie') + " Export GP Scores", export_gp_scores_path, class: 'button is-warning' %>
  </div>
</main>

app/views/welcome/pit.html.erb
<main id="pitDisplay">
  <%= turbo_stream_from 'pit', style: 'position: absolute;' %>
  
  <%= render 'pitDisplay' %>
</main>
<%= turbo_stream_from 'match', style: 'position: absolute;' %>
<%= render 'matchQueue' %>